
"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/1990747
===================================================================================================
Test Case      : 1990747
Description    : Verification of the ApplicationService component version using ILID value
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
Verify the ApplicationService component version.  # Helper-CmdList.sh -r ILID_DATASERVER_APPSERV_FW_VERSION <AppServ_Version>\n\n\n

Step 2 - 
The ApplicationService component version should be <AppServ_Version>

===================================================================================================


"""
import pytest

# AUTOGENERATED Test Case 1990747

# @pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
#@pytest.mark.regress_smoke
@pytest.mark.suite_id("1990124")
@pytest.mark.test_case("1990747")
def test_case(preinstalled_meter, logger, di_version):
    logger.trace("Executing Test Case 1990747 - Verification of the ApplicationService component version using ILID value")

    logger.trace('Step 1')
    as_version = preinstalled_meter.command('Helper-CmdList.sh -r ILID_DATASERVER_APPSERV_FW_VERSION')
    logger.trace('Step 2')
    assert as_version[0] == di_version



