"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/2012060
===================================================================================================
Test Case      : 2012060
Description    : Verify cosemd is up and running after the installation
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
install the given software

Step 2 - 
Meter should update with given software

Step 3 - 
Check cosemd status in meter\nps | grep -i cosem

Step 4 - 
cosemd should be up and running# ps | grep -i cosemd\n 1513 root     27948 S    cosemd\n


===================================================================================================


"""
import pytest

# AUTOGENERATED Test Case 2012060

# @pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
#@pytest.mark.regress_smoke
@pytest.mark.suite_id("2012056")
@pytest.mark.test_case("2012060")
def test_case(preinstalled_meter, logger, di_package,di_version):
    logger.trace("Executing Test Case 2012060 - Verify cosemd is up and running after the installation")

    logger.trace('Step 1')
    """AppServe will be install with preinstalled_meter fixture"""
        
    logger.trace('Step 2')
    software_version=preinstalled_meter.command('TransactionProcess --event="MUSE_V1;ReadLid;ILID_DATASERVER_APPSERV_FW_VERSION"')
    assert software_version[0].split("=")[1] == di_version
    logger.trace('Step 3')
    stdout = preinstalled_meter.command("ps | grep -i cosem")
    output = [x for x in stdout if('cosemd' in x.split()[4])]
    logger.trace('Step 4')
    assert len(output)!=0