"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase2
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/2050720
===================================================================================================
Test Case      : 2050720
Description    : Verify the default LID value of the Agent specific Agent Alarms
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
Check the lids using the command as shown: TransactionProcess --event=\"MUSE_V1;ReadLid;
ILID_DATASERVER_AGENT_ALARM_LIMIT\";\n

Step 2 - 
The default value is 10 messages


===================================================================================================


"""
import pytest
from tests.test_meters.rohan_utils import absolute_command

# AUTOGENERATED Test Case 2050720

# @pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
# @pytest.mark.regress_smoke
@pytest.mark.suite_id("2050431")
@pytest.mark.test_case("2050720")
def test_case(preinstalled_meter, logger):
    logger.trace("Executing Test Case 2050720 - Verify the default LID value of the Agent specific Agent Alarms")
    logger.trace('Step 1')
    stdout = absolute_command(preinstalled_meter,'TransactionProcess --event="MUSE_V1;ReadLid; ILID_DATASERVER_AGENT_ALARM_LIMIT";')
    logger.trace('Step 2')
    lid = stdout[0].split('=')[1]
    assert "10" in lid

    


