
"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase2
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/2050724
===================================================================================================
Test Case      : 2050724
Description    : Verify the installation of latest AppServ package with DI-Agent provided by the Agent team using ImProv method
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
Do a GMR. /usr/share/itron/scripts/GlobalMeterReset.sh

Step 2 - 


Step 3 - 
Install the latest appserv package using the command: ImProvHelper.sh --image <DI Appserv.tar.gz>

Step 4 - 
Check using these two command if its installed with the latest Version: TransactionProcess
--event=\"MUSE_V1;ReadLid;ILID_APP_SERVICE_PKG_INSTALLED\"\nTransactionProcess
--event=\"MUSE_V1;ReadLid;ILID_DATASERVER_APPSERV_FW_VERSION\"

Step 5 - 
Do not set these two lids: TransactionProcess --event=\"MUSE_V1;ReadLid;
ILID_DATASERVER_AGENT_HEADEND_DATA_LIMIT\";\nTransactionProcess --event=\"MUSE_V1;ReadLid;
ILID_DATASERVER_AGENT_ALARM_LIMIT\";

Step 6 - 
Let it be default. # TransactionProcess --event=\"MUSE_V1;ReadLid; ILID_DATASERVER_AGENT_HEADEND_DAT
A_LIMIT\";\nRESULT:SUCCESS:ILID_DATASERVER_AGENT_HEADEND_DATA_LIMIT:U32=10240\n# TransactionProcess
--event=\"MUSE_V1;ReadLid;
ILID_DATASERVER_AGENT_ALARM_LIMIT\";\nRESULT:SUCCESS:ILID_DATASERVER_AGENT_ALARM_LIMIT:U32=10

Step 7 - 
Install the agent either using FDM or ImProvHelper.sh

Step 8 - 
Agent should be up and running with its PID and agent name


===================================================================================================


"""
import pytest
from itron.meter.Gen5Meter import ParallelMeter
from tests.test_meters.utils import  install_agent_and_activate, DI_TEST_AGENT,wait_for_agents,is_process_running,filter_ps


# AUTOGENERATED Test Case 2050724

#@pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
@pytest.mark.regress_smoke
@pytest.mark.suite_id("2050497")
@pytest.mark.gmr_meter
@pytest.mark.slow1020
@pytest.mark.test_case("2050724")
@pytest.mark.parametrize("agent_info", [DI_TEST_AGENT])
def test_case(meter, logger,di_package,agent_info,di_version):
     with ParallelMeter(meter,logger) as remote_meter:
        logger.trace("Executing Test Case 2050724 - Verify the installation of latest AppServ package with DI-Agent provided by the Agent team using ImProv method")

        logger.trace('Step 1')
        remote_meter.gmr()
        logger.trace('Step 2')
        logger.trace('Step 3')
        remote_meter.install(file=di_package)
        logger.trace('Step 4')
        std_out1=remote_meter.command('TransactionProcess --event="MUSE_V1;ReadLid;ILID_APP_SERVICE_PKG_INSTALLED;"')
        std_out1=std_out1[0].split("=")[-1]
        assert "true" in std_out1, "APP_SERVICE_PKG is not INSTALLED"
        std_out2=remote_meter.command('TransactionProcess --event="MUSE_V1;ReadLid;ILID_DATASERVER_APPSERV_FW_VERSION"')
        std_out2=std_out2[0].split("=")[-1]
        assert di_version in std_out2, "it is not installed with the latest Version"
        logger.trace('Step 5')
        headend_data_lid=remote_meter.command('TransactionProcess --event="MUSE_V1;ReadLid;ILID_DATASERVER_AGENT_HEADEND_DATA_LIMIT;"')
        headend_data_lid=headend_data_lid[0].split("=")[-1]
        agent_alarm_lid=remote_meter.command('TransactionProcess --event="MUSE_V1;ReadLid;ILID_DATASERVER_AGENT_ALARM_LIMIT;"')
        agent_alarm_lid=agent_alarm_lid[0].split("=")[-1]
        logger.trace('Step 6')
        assert "10240" in headend_data_lid, "APP_SERVICE_PKG is not INSTALLED"
        assert "10" in agent_alarm_lid, "agent alarm limit not set to default"
        logger.trace('Step 7')
        install_agent_and_activate(remote_meter,logger,agent_info)
        logger.trace('Step 8')
        assert is_process_running(remote_meter,f'{agent_info.name}_Daemon'),"Agent is not up "
        agent_pid=filter_ps(remote_meter,f'{agent_info.name}_Daemon')[0][0]
        assert int(agent_pid) > 0,"Agent is not running with valid PID"


                                                                     