"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/1990733
===================================================================================================
Test Case      : 1990733
Description    : Verify the provided package is a coldstart package of ApplicationServices Install Packages on the Build location
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
Goto the build path location and find the latest build.

Step 2 - 
-

Step 3 - 
Verify the name of the .zip file.

Step 4 - 
Name of   the file should contains \"DI-AppServices-Package-1.0.xx.0_TS.tar.gz\" keyword

Step 5 - 
Verify the size of the tar.gz file.

Step 6 - 
Size of the file should be more than  ex: 600KB


===================================================================================================


"""
import pytest
import re
import os

# AUTOGENERATED Test Case 1990733

# @pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
#@pytest.mark.regress_smoke
@pytest.mark.suite_id("1990123")
@pytest.mark.test_case("1990733")
def test_case(logger, appserve_artifacts):
    logger.trace("Executing Test Case 1990733 - Verify the provided package is a coldstart package of ApplicationServices Install Packages on the Build location") 
    logger.trace('Step 1')
    """appserve_artifacts fixture is the build path location and find the latest build"""
    logger.trace('Step 2')
    logger.trace('Step 3')
    build_package = appserve_artifacts.di_package
    result = re.search('FinalPackage/(.*)', build_package)
    result = result.group(1)
    logger.trace('Step 4')
    assert "DI-AppServices-Package-" in result and "_TS.zip" in result
    logger.trace('Step 5')
    file_size_bytes = os.path.getsize(build_package)
    file_size_kb = file_size_bytes/1024
    logger.trace('Step 6')
    assert file_size_kb > 600, "File size less than 600kb"


