
"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1/AppServ-Installation
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/1993241
===================================================================================================
Test Case      : 1993241
Description    : Verify CMD creates a directory called /tmp/container
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
Verify that CMD creates a directory /tmp/container

Step 2 - 
/tmp/container directory should be seen in the host system


===================================================================================================


"""
import pytest
from itron.meter.Gen5Meter import ParallelMeter

# AUTOGENERATED Test Case 1993241

# @pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
#@pytest.mark.regress_smoke
@pytest.mark.suite_id("1993280")
@pytest.mark.test_case("1993241")
@pytest.mark.slow1020 # test takes 10 to 20 minutes
@pytest.mark.gmr_meter
def test_case(meter, logger):
    with ParallelMeter(meter,logger) as remote_meter:
        logger.trace("Executing Test Case 1993241 - Verify CMD creates a directory called /tmp/container")

        logger.trace('Step 1')
        remote_meter.gmr()
        logger.trace('Step 2')
        dir = remote_meter.command('cd /tmp/; ls | grep container')
        assert 'container' in dir


