
"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase2
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/2051288
===================================================================================================
Test Case      : 2051288
Description    : Verify if the default daily outcome data limit is stored as a LID value using TP command
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
Check the lids using the command as shown: TransactionProcess --event=\"MUSE_V1;ReadLid;
ILID_DATASERVER_AGENT_HEADEND_DATA_LIMIT\";\n

Step 2 - 
You should be able to see the lid value set.  TransactionProcess --event=\"MUSE_V1;ReadLid;ILID_DATA
SERVER_AGENT_HEADEND_DATA_LIMIT\"RESULT:SUCCESS:ILID_DATASERVER_AGENT_HEADEND_DATA_LIMIT:U32=10240\n


===================================================================================================


"""
import pytest
from tests.test_meters.rohan_utils import absolute_command

#AUTOGENERATED Test Case 2051288
#@pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
#@pytest.mark.regress_smoke
@pytest.mark.suite_id("2050497")
@pytest.mark.test_case("2051288")
def test_case(preinstalled_meter, logger, di_version):
    logger.trace("Executing Test Case 2051288 - Verify if the default daily outcome data limit is stored as a LID value using TP command")
    logger.trace('Step 1')
    std_out=absolute_command(preinstalled_meter,'TransactionProcess --event="MUSE_V1;ReadLid;ILID_DATASERVER_AGENT_HEADEND_DATA_LIMIT;"')
    std_out=std_out[0].split("=")[-1]
    logger.trace('Step 2')
    assert "10240" in std_out, "APP_SERVICE_PKG is not INSTALLED"


