"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/1999897
===================================================================================================
Test Case      : 1999897
Description    : Deployment of the Latest ApplicationService component package (ColdStart Package) on the RIVA firmware using 4.1 and 4.2 Meters using Net Manager method
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 -
Deployment of A7 through Improv.
/usr/bin/ImProvHelper.sh --image  <Firmware_Image>

Step 2 -
# TransactionProcess --event=\"MUSE_V1;ReadLid;ILID_SYSTEM_FW_VERSION;\"\nRESULT:SUCCESS:ILID_SYSTEM
_FW_VERSION:String=<A7_Firmware_Version>\n

Step 3 -
Deployment of ApplicationService Package through Improv.                /usr/bin/ImProvHelper.sh
--image <AppServ_Package>

Step 4 -
# TransactionProcess --event=\"MUSE_V1;ReadLid;ILID_DATASERVER_APPSERV_FW_VERSION;\"\nRESULT:SUCCESS
:ILID_DATASERVER_APPSERV_FW_VERSION:String=<AppServ_Version>\n# TransactionProcess --event=\"MUSE_V1
;ReadLid;ILID_APP_SERVICE_PKG_INSTALLED;\"\nRESULT:SUCCESS:ILID_APP_SERVICE_PKG_INSTALLED:Bool=true\
n


===================================================================================================


"""
import pytest
from itron.meter.Gen5Meter import ParallelMeter

# AUTOGENERATED Test Case 1999897F
# @pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_weekly
# @pytest.mark.regress_nightly
#@pytest.mark.regress_smoke
@pytest.mark.suite_id("1990124")
@pytest.mark.test_case("1999897")

def test_case(meter, logger,di_package, fw_ver):

    with ParallelMeter(meter,logger) as remote_meter:
        logger.trace("Executing Test Case 1999897 - Deployment of the Latest ApplicationService component package (ColdStart Package) on the RIVA firmware using 4.1 and 4.2 Meters using Net Manager method")
        logger.trace('Step 1')
        remote_meter.coldstart(version=fw_ver)
        fwver, asver = remote_meter.version_info()
        logger.trace("Current versions: fw:%s as:%s", fwver, asver)
        logger.trace('Step 2')
        fw_VERSION=remote_meter.command('TransactionProcess --event="MUSE_V1;ReadLid;ILID_SYSTEM_FW_VERSION;"')
        fw_VERSION = fw_VERSION[0].split('=')
        assert fw_VERSION[1]==fwver

        logger.trace('Step 2')
        remote_meter.install(file=di_package)
        fwver, asver = remote_meter.version_info()
        logger.trace('Step 2')
        as_VERSION=remote_meter.command('TransactionProcess --event="MUSE_V1;ReadLid;ILID_DATASERVER_APPSERV_FW_VERSION"')
        as_VERSION = as_VERSION[0].split('=')
        assert as_VERSION[1]==asver






