"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/1992828
===================================================================================================
Test Case      : 1992828
Description    : Verify that the hash authentication is successful on upgrade logs
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
Remove all logs using below command:
rm /mnt/pouch/LifeBoatLogs/*ImProv*

Step 2 - 
verify the files are removed using below command:
ls /mnt/pouch/LifeBoatLogs/*ImProv*

Step 3-
GMR the meter
/usr/share/itron/scripts/GlobalMeterReset.sh

Step 4-
Install the latest App-services

Step 5=
After App-serv installation check Improv files using below command:
 ls /mnt/pouch/LifeBoatLogs/*ImProv*

Step 6 =
gunzip /mnt/pouch/LifeBoatLogs/ImProv.txt.0054887708018.2022-12-22-0001671701056.304.gz

Step 7=
cat /mnt/pouch/LifeBoatLogs/ImProv.txt.0054887708018.2022-12-22-0001671701056.304
===================================================================================================


"""
import pytest
import os
from tempfile import TemporaryDirectory
import gzip
# AUTOGENERATED Test Case 1992828

@pytest.mark.skip(reason="modification requires as per BUG 2953758")
@pytest.mark.regress_nightly
@pytest.mark.slow1020 # test takes 10 to 20 minutes
#@pytest.mark.regress_smoke
@pytest.mark.suite_id("1990123")
@pytest.mark.test_case("1992828")
@pytest.mark.gmr_meter
def test_case(preinstalled_meter, logger, di_package):
    logger.trace("Executing Test Case 1992828 - Verify that the hash authentication is successful on upgrade logs")
    logger.trace('Step 1')
    preinstalled_meter.command("rm /mnt/pouch/LifeBoatLogs/*ImProv*")
    logger.trace('Step 2')
    preinstalled_meter.command("ls /mnt/pouch/LifeBoatLogs/*ImProv*")
    logger.trace('step-3')
    preinstalled_meter.gmr()
    logger.trace('step-4')
    preinstalled_meter.install(file=di_package)
    logger.trace('step-5')
    LifeBoat=preinstalled_meter.command("ls /mnt/pouch/LifeBoatLogs/*ImProv*")
    assert len(LifeBoat)!=0
    logger.trace('step-6')
    Impov=preinstalled_meter.command('ls /mnt/pouch/LifeBoatLogs/ | grep ImProv.txt')

    with TemporaryDirectory() as d:
        tempgz=os.path.join(d, "temp.gz")
        preinstalled_meter.get_file(f"/mnt/pouch/LifeBoatLogs/{Impov[1]}", tempgz)
        with gzip.open(tempgz, 'rb') as f:
            file_data = f.read()
            logger.trace(file_data.decode("utf-8"))
            print(type(file_data))

    logger.trace('step-7')
    assert "Hash authentication successfully" in file_data.decode("utf-8")

