"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase2
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/2050374
===================================================================================================
Test Case      : 2050374
Description    : Verify the behavior of the counter service table after GMR
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
After GMR verify the AgentFeatureDataCounter table.

Step 2 - 
AgentFeatureDataCounter table should not exists after GMR.

Step 3 - 
After GMR, install AppService package and verify if the AgentFeatureDataCounter table exists.

Step 4 - 
AgentFeatureDataCounter table should exist.


===================================================================================================


"""
import pytest
from itron.meter.Gen5Meter import ParallelMeter

# AUTOGENERATED Test Case 2050374

# @pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.slow1020   #takes 10 to 20 minutes
@pytest.mark.regress_nightly
#@pytest.mark.regress_smoke
@pytest.mark.suite_id("2046635")
@pytest.mark.test_case("2050374")
@pytest.mark.gmr_meter
def test_case(meter, logger, di_package):
    with ParallelMeter(meter,logger) as remote_meter:
        logger.trace("Executing Test Case 2050374 - Verify the behavior of the counter service table after GMR")
        logger.trace('Step 1')
        remote_meter.gmr()
        logger.trace('Step 2')
        AgentFeatureDataCounterTable =remote_meter.sql_query(".tables 'AgentFeatureData%'")
        logger.trace(AgentFeatureDataCounterTable)
        assert len(AgentFeatureDataCounterTable) == 0,"AgentFeatureDataCounter table is present after GMR"
        logger.trace('Step 3')
        remote_meter.install(file=di_package)
        AgentFeatureDataCounterTable =remote_meter.sql_query(".tables 'AgentFeatureData%'")
        logger.trace('Step 4')
        assert 'AgentFeatureDataCounter' in AgentFeatureDataCounterTable,"AgentFeatureDataCounter table is not present after Appserve Installation"


