
"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1/AppServ-Installation
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/1993238
===================================================================================================
Test Case      : 1993238
Description    : Verify that LXC package should be available for the platform  
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
goto /usr/bin
cd /usr/bin/

Verify all the LXC package available in /usr/bin
ls lxc-*

Step 2 - 
lxc-attach         lxc-checkpoint     lxc-create         lxc-freeze         lxc-snapshot       lxc-unfreeze       lxc-wait
lxc-autostart      lxc-config         lxc-destroy        lxc-info           lxc-start          lxc-unshare
lxc-cgroup         lxc-console        lxc-device         lxc-ls             lxc-stop           lxc-update-config
lxc-checkconfig    lxc-copy           lxc-execute        lxc-monitor        lxc-top            lxc-usernsexec



===================================================================================================


"""
import pytest
from tests.test_meters.utils import DI_TEST_AGENT,install_agent_and_activate

# AUTOGENERATED Test Case 1993238

# @pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
 
#@pytest.mark.regress_smoke
@pytest.mark.suite_id("1993280")
@pytest.mark.test_case("1993238")
@pytest.mark.parametrize("agent_info", [DI_TEST_AGENT])
def test_case(preinstalled_meter, logger, agent_info):
    logger.trace("Executing Test Case 1993238 - Verify that LXC package should be available for the platform  ")

    logger.trace('Step 1')
    install_agent_and_activate(preinstalled_meter, logger, agent_info)
    lxc_pckg = preinstalled_meter.command('cd /usr/bin/;ls lxc-*')
    logger.trace(lxc_pckg)
    logger.trace('Step 2')
    list_to_check = ['lxc-attach', 'lxc-autostart', 'lxc-cgroup', 'lxc-checkconfig', 'lxc-checkpoint', 'lxc-config', 'lxc-console',
        'lxc-copy', 'lxc-create', 'lxc-destroy', 'lxc-device', 'lxc-execute', 'lxc-freeze', 'lxc-info', 'lxc-ls', 'lxc-monitor',
        'lxc-snapshot', 'lxc-start', 'lxc-stop', 'lxc-top', 'lxc-unfreeze', 'lxc-unshare', 
        'lxc-update-config', 'lxc-usernsexec', 'lxc-wait']
    for x in list_to_check:
        assert x in lxc_pckg


