
"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1/AppServ-Installation
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/1993243
===================================================================================================
Test Case      : 1993243
Description    : Verify on start-up CMD checks the ILID_CONTAINERS_RUN_ON_STARTUP flag and runs/does not run containers 
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
Ensure agent & lxc are running
pgrep lxc

Step 2 - 
 lxc process will be listed

Step 3 -
Set the ILID_CONTAINERS_RUN_ON_STARTUP to false using below command:
TransactionProcess --event="MUSE_V1;WriteLid;ILID_CONTAINERS_RUN_ON_STARTUP;false"

Step 4 -

Step 5 -
reboot the meter & verify lxc is not running
pgrep lxc

Step 6 -
lxc will not be running
 
Step 7 -
Set the ILID_CONTAINERS_RUN_ON_STARTUP to true using below command:
TransactionProcess --event="MUSE_V1;WriteLid;ILID_CONTAINERS_RUN_ON_STARTUP;true"

Step 8 -

Step 9 -
Refresh the container 

Step 10 -

===================================================================================================


"""
import pytest
import time
from tests.test_meters.utils import install_agent_and_activate,HAN_AGENT,refresh_container,is_process_running,write_lid,get_installed_agents,wait_for_agents,read_lid,stop_container

# AUTOGENERATED Test Case 1993243

# @pytest.mark.skip(reason="PR BLOCKER")
@pytest.mark.regress_nightly
@pytest.mark.regress_smoke
@pytest.mark.suite_id("1993280")
@pytest.mark.test_case("1993243")
def test_case(preinstalled_meter, logger):
    logger.trace("Executing Test Case 1993243 - Verify on start-up CMD checks the ILID_CONTAINERS_RUN_ON_STARTUP flag and runs/does not run containers ")

    logger.trace('Step 1')

    installed_agents = get_installed_agents(preinstalled_meter,logger)

    if installed_agents:
        wait_for_agents(preinstalled_meter, logger, installed_agents, 20*60)
    else:
        install_agent_and_activate(preinstalled_meter, logger, HAN_AGENT)

    ilid = 'ILID_CONTAINERS_RUN_ON_STARTUP'
    default_value = read_lid(preinstalled_meter,logger,ilid)

    logger.trace('Step 2')
    assert is_process_running(preinstalled_meter,"lxc-start"),'Container is not running'

    try:
        
        logger.trace('Step 3')
        value = False
        write_lid(preinstalled_meter,logger,ilid,value)

        logger.trace('Step 4')
        logger.trace('Step 5')
        preinstalled_meter.reboot_meter()
        logger.trace('Step 6')
        assert not is_process_running(preinstalled_meter,"lxc-start"),'Container is still running after reboot'

        logger.trace('Step 7')
        value = True
        write_lid(preinstalled_meter,logger,ilid,value)

        logger.trace('Step 8')
        logger.trace('Step 9')
        refresh_container(preinstalled_meter,logger,20*60)
        logger.trace('Step 10')
        assert is_process_running(preinstalled_meter,"lxc-start"),'Container is not running'

    finally:
        write_lid(preinstalled_meter,logger,ilid,default_value)
        stop_container(preinstalled_meter)
        refresh_container(preinstalled_meter,logger,20*60)