
"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1/AppServ-Installation
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/1993224
===================================================================================================
Test Case      : 1993224
Description    : 	CMStopAllContainer
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
Check whether multiple containers can be stopped using Dbus StopAllContainer signal.  dbus-send
--print-reply --system --dest=com.itron.museplatform.ContainerManager
/com/itron/museplatform/ContainerManager com.itron.museplatform.ContainerManager.StopAllContainer

Step 2 - 

Step 3 - 
Check no container is running "lxc-start"

Step 4 - 
No container should be running


===================================================================================================


"""
import pytest
import time
from tests.test_meters.utils import Third_Party_PubSub_AGENT,install_agent_and_activate,stop_container,refresh_container



# AUTOGENERATED Test Case 1993224

#@pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
#@pytest.mark.regress_smoke
@pytest.mark.suite_id("1993280")
@pytest.mark.test_case("1993224")
@pytest.mark.parametrize("agent_info", [Third_Party_PubSub_AGENT])
def test_case(preinstalled_meter, logger, agent_info):
    logger.trace("Executing Test Case 1993224 - \tCMStopAllContainer")
    logger.trace('Step 1')
    install_agent_and_activate(preinstalled_meter, logger, agent_info)
    container_id=preinstalled_meter.ls("/tmp/container")
    assert '587464704' in container_id
    try:
        stop_container(preinstalled_meter)

    finally:
        refresh_container(preinstalled_meter,logger,20*60)
    






