
"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1/AppServ-Installation
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/1993229
===================================================================================================
Test Case      : 1993229
Description    : CONTAINERSETUP_Table
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
Verify that the container installed using HID Agent package matches to the ContainerSetup table
sqlite3 /mnt/common/database/muse01.db \"select * from CONTAINERSETUP\"

Step 2 - 
UID should match to the running container.


===================================================================================================


"""
import pytest
from tests.test_meters.utils import install_agent_and_activate,HAN_AGENT

# AUTOGENERATED Test Case 1993229

# @pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
 
#@pytest.mark.regress_smoke
@pytest.mark.suite_id("1993280")
@pytest.mark.test_case("1993229")
def test_case(preinstalled_meter, logger):
    logger.trace("Executing Test Case 1993229 - CONTAINERSETUP_Table")

    logger.trace('Step 1')
    install_agent_and_activate(preinstalled_meter, logger, HAN_AGENT)
    logger.trace('Step 2')
    uid_from_table = preinstalled_meter.sql_query("select UID from CONTAINERSETUP")
    assert HAN_AGENT.container_id in uid_from_table


