
"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1/AppServ-Installation
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/1993232
===================================================================================================
Test Case      : 1993232
Description    : ILID_WATCHDOG_TIMING_Default_Value
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
Verify the default value of ILID_CONTAINERS_WATCHDOG_TIMING_MS TransactionProcess
--event=\"MUSE_V1;ReadLid;ILID_CONTAINERS_WATCHDOG_TIMING_MS\"

Step 2 - 
ILID_CONTAINERS_WATCHDOG_TIMING_MS default value should match to the container design document
value. - # TransactionProcess --event=\"MUSE_V1;ReadLid;ILID_CONTAINERS_WATCHDOG_TIMING_MS\"\nRESULT
:SUCCESS:ILID_CONTAINERS_WATCHDOG_TIMING_MS:U32=300000


===================================================================================================


"""
import pytest

# AUTOGENERATED Test Case 1993232

# @pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
@pytest.mark.regress_smoke
@pytest.mark.suite_id("1993280")
@pytest.mark.test_case("1993232")
def test_case(preinstalled_meter, logger):
    logger.trace("Executing Test Case 1993232 - ILID_WATCHDOG_TIMING_Default_Value")

    logger.trace('Step 1')
    ILID_WATCHDOG_TIMING_Default_Value = preinstalled_meter.command('TransactionProcess --event="MUSE_V1;ReadLid;ILID_CONTAINERS_WATCHDOG_TIMING_MS"')
    ILID_WATCHDOG_TIMING_Default_Value = ILID_WATCHDOG_TIMING_Default_Value[0].split('=')
    logger.trace('Step 2')
    assert '300000' == ILID_WATCHDOG_TIMING_Default_Value[1],'ILID_WATCHDOG_TIMING_Default_Value not matching'

