
"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1/AppServ-Installation
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/1993236
===================================================================================================
Test Case      : 1993236
Description    : Verify that only one CMD is running in the system or not
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
Check whether only one Container Manager daemon(CMD) is running on the platform or notps | grep -i
contain

Step 2 - 
\'ps\' command output should show the CMD if it is running and one should not see multiple CMD


===================================================================================================


"""
import pytest

# AUTOGENERATED Test Case 1993236

# @pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
#@pytest.mark.regress_smoke
@pytest.mark.suite_id("1993280")
@pytest.mark.test_case("1993236")
def test_case(preinstalled_meter, logger):
    logger.trace("Executing Test Case 1993236 - Verify that only one CMD is running in the system or not")

    logger.trace('Step 1')
    cmd_output = preinstalled_meter.command('ps | grep contain')
    cmd = [x for x in cmd_output if('ContainerManager' in x.split()[4] and 'Z' not in x.split()[3])]
    logger.trace('Step 2')
    assert len(cmd) == 1


