"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1/AppServ-Installation
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/1993230
===================================================================================================
Test Case      : 1993230
Description    : CONTAINERSTATUS_Table
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 -
Verify that the running container matches to the GUID of the /tmp/Containerstatus table   # sqlite3
--header  /tmp/muse01.db \"select * from CONTAINERSTATUS;\"

Step 2 -
Container running on the system should match to the GUID of /tmp/containerstatus

===================================================================================================

"""
import pytest
import time
from tests.test_meters.utils import install_agent_and_activate,Third_Party_PubSub_AGENT,Active_Containers

# AUTOGENERATED Test Case 1993230

#@pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
 
@pytest.mark.slow1020 # test takes 10 to 20 minutes
@pytest.mark.suite_id("1993280")
@pytest.mark.test_case("1993230")
@pytest.mark.parametrize("agent_info", [Third_Party_PubSub_AGENT])
def test_case(preinstalled_meter, logger,agent_info):
    logger.trace("Executing Test Case 1993230 - CONTAINERSTATUS_Table")
    logger.trace('Step 1')
    install_agent_and_activate(preinstalled_meter, logger, agent_info)
    assert '587464704' in Active_Containers(preinstalled_meter),"""container ID not found"""
    logger.trace('Step 2')
    stop = time.time() + (90)
    while time.time()<=stop:

        time_out=time.time() + 10
        while time_out>time.time():    
            code,guid_list=preinstalled_meter.command_with_code("sqlite3 /tmp/muse01.db 'select GUID from CONTAINERSTATUS;'")
            if code == 0:
                break
            time.sleep(2)

        if '587464704' in guid_list:
            break
        else:
            time.sleep(5)
    assert '587464704' in guid_list,"timeout for condition check"


