
"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/2004766
===================================================================================================
Test Case      : 2004766
Description    : Verify that the Container Manager resource limits are properly handled
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 -
Check for the default values of the below lids:#TransactionProcess
--event=\"MUSE_V1;ReadLid;ILID_CONTAINER_MAX_FLASH_LIMIT_KB\"#TransactionProcess
--event=\"MUSE_V1;ReadLid;ILID_CONTAINER_MAX_MEMORY_LIMIT_KB\"

Step 2 -
# TransactionProcess --event=\"MUSE_V1;ReadLid;ILID_CONTAINER_MAX_FLASH_LIMIT_KB\"\nRESULT:SUCCESS:I
LID_CONTAINER_MAX_FLASH_LIMIT_KB:U32=40000# TransactionProcess --event=\"MUSE_V1;ReadLid;ILID_CONTAI
NER_MAX_MEMORY_LIMIT_KB\"\nRESULT:SUCCESS:ILID_CONTAINER_MAX_MEMORY_LIMIT_KB:U32=65000\n

Step 3 -
Create configurations with known resource consumption (flash, memory).  Decrease the default LID
limits for container maximum memory and flash memory  and check if the container is not starting.
Ensure there are 2 containers in the meter. Install both Itron and ThrirdParty agent for it and
execute the below steps.

Step 4 -
Containers should be allowed to start when the ILID values are greater-than or equal-to their
configured usage. Otherwise, they should not be allowed to start and a DB log event should be
recorded with the reason.

Step 5 -
# TransactionProcess --event=\"MUSE_V1;WriteLid;ILID_CONTAINER_MAX_MEMORY_LIMIT_KB;65\"Stop
container and refresh it with the below commands.#dbus-send --type=signal --system
--dest=com.itron.museplatform.ContainerManager /com/itron/museplatform/ContainerManager
com.itron.museplatform.ContainerManager.StopAllC\nontainer#dbus-send --type=signal --system
--dest=com.itron.museplatform.ContainerManager /com/itron/museplatform/ContainerManager
com.itron.museplatform.ContainerManager.Refresh

Step 6 -


Step 7 -
Check the containermanager log #cdsEventLogDecoderV2 -f1 -i
/mnt/pouch/LifeBoatLogs/ContainerManager.txt

Step 8 -
Check for this error in the log. \"{2022/12/13 10:11:07 [44690296.176]}\",\"None\",\"Unable to start
container 587464704. Reason: Memory limit
exceeded\",\"ERROR\",\"ContainerManager\",\"\",\"\",\"10.5.764.2 (Best
Guess)\",\"MUSE\",\"36\",\"5470\"


===================================================================================================


"""
import pytest
import time
from tests.test_meters.utils import Active_Containers,read_lid,refresh_container,stop_container, write_lid, install_multiple_agents_and_activate,wait_for_agents,Third_Party_PubSub_AGENT,DI_TEST_AGENT,refresh_container
from tests.test_meters.event_utils import get_meter_system_time, wait_for_eventlog_entry,wait_for_eventlog_entry_with_rotator

# AUTOGENERATED Test Case 2004766

#@pytest.mark.skip(reason="get_meter_time shouldn't be used for getting the current time")
@pytest.mark.regress_nightly
@pytest.mark.regress_smoke
@pytest.mark.suite_id("2002265")
@pytest.mark.test_case("2004766")
def test_case(preinstalled_meter, logger):
    logger.trace("Executing Test Case 2004766 - Verify that the Container Manager resource limits are properly handled")
    logger.trace('Step 1')
    lid="ILID_CONTAINER_MAX_FLASH_LIMIT_KB"
    Flash_limit=read_lid(preinstalled_meter,logger,lid)
    lid="ILID_CONTAINER_MAX_MEMORY_LIMIT_KB"
    Memory_limit=read_lid(preinstalled_meter,logger,lid)

    test_start = get_meter_system_time(preinstalled_meter)
    logger.info("Start: %s", test_start)
    logger.trace('Step 2')
    try:
        assert Flash_limit==40000,"Default value of Container Max Flash Limit is not set"
        assert Memory_limit==65000,"Default value of Container Max Memory Limit is not set"
        logger.trace('Step 3')
        agent_list=[Third_Party_PubSub_AGENT,DI_TEST_AGENT]
        install_multiple_agents_and_activate(preinstalled_meter, logger, agent_list)
        logger.trace('Step 4')
        logger.trace('Step 5')
        lid,value="ILID_CONTAINER_MAX_MEMORY_LIMIT_KB",65
        write_lid(preinstalled_meter,logger,lid,value)
        stop_container(preinstalled_meter)
        preinstalled_meter.command("dbus-send --type=signal --system --dest=com.itron.museplatform.ContainerManager /com/itron/museplatform/ContainerManager com.itron.museplatform.ContainerManager.Refresh")
        logger.trace('Step 6')
        logger.trace('Step 7')
        logger.trace('Step 8')

        check=f"Unable to start container {Third_Party_PubSub_AGENT.container_id}. Reason: Memory limit exceeded"
        wait_for_eventlog_entry_with_rotator(preinstalled_meter, logger, test_start, 
        "/mnt/pouch/LifeBoatLogs/ContainerManager.txt", check, 5*60)
        
    finally:
        lid="ILID_CONTAINER_MAX_FLASH_LIMIT_KB"
        write_lid(preinstalled_meter,logger,lid,40000)
        lid="ILID_CONTAINER_MAX_MEMORY_LIMIT_KB"
        write_lid(preinstalled_meter,logger,lid,65000)
        
        stop_container(preinstalled_meter)
        refresh_container(preinstalled_meter, logger, 20*60)

