
"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/2715536
===================================================================================================
Test Case      : 2715536
Description    : Verify that Container Manager does notify all system processes and daemons through the system Dbus service that the LXC Container is started
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
Stop the container using below command: dbus-send --type=signal --system
--dest=com.itron.museplatform.ContainerManager /com/itron/museplatform/ContainerManager
com.itron.museplatform.ContainerManager.StopAllContainer

Step 2 - 
All running Containers should be stopped

Step 3 - 
remove ContainerManager.txt file using below command:rm
/tmp/logs/ContainerManager/INFORMATION/ContainerManager.txt

Step 4 - 

Step 5- 
Start the containers with the below command:dbus-send --type=signal --system
--dest=com.itron.museplatform.ContainerManager /com/itron/museplatform/ContainerManager
com.itron.museplatform.ContainerManager.Refresh\n

Step 6 - 
containers should be started

Step 7 - 
Ensure Agent & containers are running:ps|grep Agent ps|grep lxc-start

Step 8 - 
7256 containe  7232 S    /usr/bin/0302ff80/DITestAgent_Daemon7196 containe  2032 S    lxc-start -d
-P /tmp/container -n 50593792

Step 9 - 
Check the container log cat /tmp/logs/ContainerManager/INFORMATION/ContainerManager.txt

Step 10 - 
3325344335890  5 None 22 Refresh container dbus 134217734 1671618214.595771911|71526345.923462592
1869 ContainerManager 0  0  0 0 0 0 1 48 1 1869  EOR 5 None 503 Container 50593792 mounted is lowerd
ir=/tmp/container/lowerOverlay/50724736:/tmp/container/lowerOverlay/50659333:/tmp/container/lowerOve
rlay/50659330:/tmp/container/lowerOverlay/33882114:/tmp/container/lowerOverlay/17039365:/tmp/contain
er/lowerOverlay/33816577:/tmp/container/lowerOverlay/17039362:/tmp/container/lowerOverlay/17039364:/
tmp/container/lowerOverlay/17039363:/tmp/container/lowerOverlay/17039361,upperdir=/tmp/container/505
93792/upperOverlay/,workdir=/tmp/container/50593792/workingOverlay/ 134217734
1671618217.468322927|71526348.795503679 1869 ContainerManager 0  0  0 0 0 0 1 48 1 1869  EOR 5 None
67 50593792 flash image path is /media/mmcblk0p1/lxc/50593792/50724736 134217734
1671618217.727916147|71526349.055011706 1869 ContainerManager 0  0  0 0 0 0 1 48 1 1869  EOR 5 None
41 Started the container with name 50593792. 134217734 1671618224.045112816|71526355.371422394 1869
ContainerManager 0  0  0 0 0 0 1 48 1 1869  EOR 5 None 99 GetContainerPath: Container ID 50593792
Path:unix:path=/tmp/container/50593792/container_bus_socket 134217734
1671618224.100063938|71526355.426209416 1869 ContainerManager 0  0  0 0 0 0 1 48 1 1869  EOR 5 None
99 ContainerManagerApplication.cpp at [596](pid:1869/thr:1869): SendContainerInfoSignal
StartContainer 134217734 1671618224.101490715|71526355.427509376 1869 ContainerManager 0  0  0 0 0 0
1 48 1 1869


===================================================================================================


"""
import pytest
import time
from tests.test_meters.utils import is_process_running,install_agent_and_activate,is_stand_alone_init,wait_for_agents,stop_container,refresh_container,DI_TEST_AGENT

# AUTOGENERATED Test Case 2715536

# @pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
#@pytest.mark.regress_smoke
@pytest.mark.suite_id("2002265")
@pytest.mark.test_case("2715536")
def test_case(preinstalled_meter, logger):
    logger.trace("Executing Test Case 2715536 - Verify that Container Manager does notify all system processes and daemons through the system Dbus service that the LXC Container is started")

    install_agent_and_activate(preinstalled_meter,logger,DI_TEST_AGENT) 

    try:
        logger.trace('Step 1')
        stop_container(preinstalled_meter)
        logger.trace('Step 2')
        """condition checks in stop_container function"""
        logger.trace('Step 3')
        text_file="ContainerManager.txt"
        file=f"/tmp/logs/ContainerManager/INFORMATION/{text_file}"
        preinstalled_meter.command(f"rm -r {file}")

        logger.trace('Step 4')
        
    finally:
        logger.trace('Step 5') 
        logger.trace('Step 6')
        logger.trace('Step 7')
        refresh_container(preinstalled_meter, logger, 20*60)
        logger.trace('Step 8')
        assert is_process_running(preinstalled_meter,"lxc-start"),"Containers is not running"    

    logger.trace('Step 9')
    file="/tmp/logs/ContainerManager/INFORMATION/ContainerManager.txt"
    stop = time.time() + (2*60)
    while time.time()<=stop:
        Container_log=preinstalled_meter.command('cat /tmp/logs/ContainerManager/INFORMATION/ContainerManager.txt')
        Container_log = ''.join(Container_log)   
        if 'Refresh container dbus' in Container_log or 'Started the container with name 50593792' in Container_log:
            break
        else:
            time.sleep(10)
    logger.trace('Step 10')
    assert 'Refresh container dbus' in Container_log or 'Started the container with name 50593792' in Container_log,"timeout error for condition check"
           
    
        

