"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/2004402
===================================================================================================
Test Case      : 2004402
Description    : Verification of the overlay configuration of Agents
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 -
After the installation of Agents, Verify the \'overlaysetup\' table for the entry of agent
overlays.sqlite3 --header /usr/share/itron/database/muse01.db \"select * from overlaysetup\"

Step 2 -
1|50724727|0.4.24.377216952|/mnt/common/container-
overlays/ItronPubSubAgent-0302ff77.tar.bz2|1|0\n1|587595764|0.4.24.377216952|/mnt/common/container-
overlays/ThirdPartyPubSubAgent-2302fff4.tar.bz2|1|0

Step 3 -
Verify if all overlay dependencies (including necessary Itron-provided overlays)are linked to a
container by adding entries to the CONTAINEROVERLAY table. sqlite3 --header
/usr/share/itron/database/muse01.db \"select * from containeroverlay\"

Step 4 -
 # sqlite3 --header /usr/share/itron/database/muse01.db \"select * from containeroverlay\"\nGroupId|
ContainerUID|OverlayUID|LoadIndex\n1|50593792|17039361|10\n1|50593792|17039363|20\n1|50593792|170393
64|30\n1|50593792|17039362|40\n1|50593792|17039365|80\n1|50593792|50659330|200\n1|50593792|33882115|
150\n1|50593792|33882114|160\n1|50593792|33882116|170\n1|50593792|50659333|300\n1|50593792|50724727|
510\n1|50593792|33816577|50

Step 5 -
Verify any D-Bus, LXC, and Flash requirements are added to the OVERLAYCONFIGURATION table.sqlite3
--header /usr/share/itron/database/muse01.db \"select * from overlayconfiguration\"

Step 6 -
1|50724727|3|<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<!DOCTYPE busconfig PUBLIC\n
\"-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN\"\n
\"http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd\">\n\n<busconfig>\n  <policy
user=\"dserver_u\">\n    <allow send_destination=\"com.itron.owi.platform.ItronPubSubAgent\"\n
send_interface=\"com.itron.owi.platform.ItronPubSubAgent\" />\n  </policy>\n  <policy
user=\"container_dbus_u\">\n    <allow own=\"com.itron.owi.platform.ItronPubSubAgent\" />\n<allow
receive_sender=\"com.itron.owi.platform.dataserver\"/>\n    <allow
send_destination=\"com.itron.owi.platform.dataserver\"\n
send_interface=\"com.itron.owi.platform.dataserver\"/>\n  </policy>\n</busconfig> 1|50724727|1|<?xml
version=\"1.0\" encoding=\"us-ascii\"?><config version=\"1\" >\n<item
key=\"lxc.cgroup.memory.limit_in_bytes\" value=\"800000\" behaviour=\'sum\'/>\n<item
key=\"lxc.cgroup.cpu.cfs_quota_us\" value=\"4000\" behaviour=\'sum\'/>\n1|50724727|4|<?xml
version=\"1.0\" encoding=\"us-ascii\"?>\n<flashconfig version=\"1\" >\n    <flash
capacity_kib=\"1024\" mount_path=\"/usr/share/flash/50724727\"/>\n</flashconfig>\n

Step 7 -
Ensure the CONTAINERSETUP table contains a record for the container associated with the
overlays.sqlite3 --header /usr/share/itron/database/muse01.db \"select * from containersetup\"

Step 8 -
# sqlite3 --header /usr/share/itron/database/muse01.db \"select * from containersetup\"\nGroupId|UID
|DesiredState|ContainerStartDelayMS|TempFilesystemSizeBytes|PriorityLevel|IgnoreResourceUsage|Friend
lyName|DbusConnectionType\n1|50593792|1|0|8000000|20|0|Itron|1\n1|587464704|1|0|8000000|20|0|3rdPart
y|1\n


===================================================================================================


"""
import pytest
from tests.test_meters.utils import install_multiple_agents_and_activate,Third_Party_PubSub_AGENT,ITRONPUBSUBAGENT2,P2P_AGENT,DI_TEST_AGENT
import time

# AUTOGENERATED Test Case 2004402

# @pytest.mark.skip(reason="TODO: unimplemented test case")
@pytest.mark.regress_nightly
@pytest.mark.slow1020 # test takes 10 to 20 minutes
@pytest.mark.suite_id("2002265")
@pytest.mark.test_case("2004402")
def test_case(preinstalled_meter, logger):
    logger.trace("Executing Test Case 2004402 - Verification of the overlay configuration of Agents ")

    logger.trace('Step 1')
    agent_list=[Third_Party_PubSub_AGENT,ITRONPUBSUBAGENT2,P2P_AGENT,DI_TEST_AGENT]
    install_multiple_agents_and_activate(preinstalled_meter, logger, agent_list)
    time.sleep(30)
    OverlaySetup_table=preinstalled_meter.get_table("OverlaySetup")

    logger.trace('Step 2')
    for agent in agent_list:
        res = any([agent.name in sub["OverlayPath"] for sub in OverlaySetup_table])
        assert res ,f"Overlaysetup table has not entry of {agent.name}"


    logger.trace('Step 3')
    Container_id=["50593792"]
    containeroverlay_table=preinstalled_meter.get_table("containeroverlay")

    logger.trace('Step 4')
    res = all([any(con in sub["ContainerUID"] for sub in containeroverlay_table) for con in Container_id])
    assert res ,"Overlay dependencies are not linked to a container in CONTAINEROVERLAY table."

    logger.trace('Step 5')
    OVERLAYCONFIGURATION_table=preinstalled_meter.sql_query('select configuration from overlayconfiguration')

    logger.trace('Step 6')
    for agent in agent_list:
        check=[f'send_destination="com.itron.owi.platform.{agent.name}"',f'send_interface="com.itron.owi.platform.{agent.name}"',f'allow own="com.itron.owi.platform.{agent.name}"']
        res = all([any(ch in sub for sub in OVERLAYCONFIGURATION_table) for ch in check])
        assert res,"D-Bus, LXC, and Flash requirements are not added to the OVERLAYCONFIGURATION table"



    logger.trace('Step 7')
    container_uid=["50593792","587464704"]
    containeroverlay_table=preinstalled_meter.get_table("containersetup")


    logger.trace('Step 8')
    res=all([i["UID"] in container_uid for i in containeroverlay_table])
    assert res,"CONTAINERSETUP table is not contains a record for the container associated with the overlays"
