
"""
REGENRATE: True
Set REGENERATE to False if you modify this comment
section to inhibit re-writing this section
===================================================================================================
Test Plan Path : templates/AppServ-TestRepository/Phase1
Test Case Link : https://dev.azure.com/itron/SoftwareProducts/_workitems/edit/2004420
===================================================================================================
Test Case      : 2004420
Description    : Verify the permission for container-related directories and their owners
Area Path      : RnD/GFW-IVV/DI Outcomes/APP-Serve
Iteration Path : RnD/3 Week
System.History : None
Steps:
===================================================================================================
Step 1 - 
stat /mnt/common/lxc

Step 2 - 
File: /mnt/common/lxc\n  Size: 0         \tBlocks: 0          IO Block: 4096   directory\nDevice:
fe01h/65025d\tInode: 72          Links: 1\nAccess: (0755/drwxr-xr-x)  Uid: ( 1012/containerd_u)
Gid: ( 1012/containerd_g)

Step 3 - 
stat /tmp/container

Step 4 - 
File: /tmp/container\n  Size: 100       \tBlocks: 0          IO Block: 4096   directory\nDevice:
10h/16d\tInode: 8322        Links: 5\nAccess: (0777/drwxrwxrwx)  Uid: ( 1012/containerd_u)   Gid: (
1012/containerd_g)

Step 5 - 
stat /mnt/common/container-overlays

Step 6 - 
File: /mnt/common/container-overlays\n  Size: 0         \tBlocks: 0          IO Block: 4096
directory\nDevice: fe01h/65025d\tInode: 987         Links: 1\nAccess: (0755/drwxr-xr-x)  Uid: (
1012/containerd_u)   Gid: ( 1012/containerd_g)

Step 7 - 
stat /usr/share/itron/container-overlays

Step 8 - 
File: /usr/share/itron/container-overlays\n  Size: 0         \tBlocks: 0          IO Block: 4096
directory\nDevice: fe00h/65024d\tInode: 1789        Links: 1\nAccess: (0755/drwxr-xr-x)  Uid: (
0/    root)   Gid: (    0/    root)

Step 9 - 
stat /tmp/lxc_logs

Step 10 - 
File: /tmp/lxc_logs\n  Size: 60        \tBlocks: 0          IO Block: 4096   directory\nDevice:
10h/16d\tInode: 8323        Links: 2\nAccess: (0777/drwxrwxrwx)  Uid: ( 1012/containerd_u)   Gid: (
1012/containerd_g)


===================================================================================================


"""
import pytest
from tests.test_meters.utils import stat_check
from tests.test_meters.utils import DI_TEST_AGENT,install_agent_and_activate
@pytest.mark.parametrize("agent_info", [DI_TEST_AGENT])

# AUTOGENERATED Test Case 2004420

@pytest.mark.regress_nightly
#@pytest.mark.regress_smoke
@pytest.mark.suite_id("2002265")
@pytest.mark.test_case("2004420")
def test_case(preinstalled_meter,agent_info, logger):
    logger.trace("Executing Test Case 2004420 - Verify the permission for container-related directories and their owners")
    install_agent_and_activate(preinstalled_meter, logger, agent_info)
    logger.trace('Step 1')
    dir="/mnt/common/lxc"
    list_check=["0755","containerd_u","containerd_g"]

    logger.trace('Step 2')
    assert stat_check(preinstalled_meter,dir,list_check),f"File {dir} doesn't have a permission for container-related directories and their owners"

    logger.trace('Step 3')
    dir="/tmp/container"
    list_check=["0777","containerd_u","containerd_g"]

    logger.trace('Step 4')
    assert stat_check(preinstalled_meter,dir,list_check),f"File {dir} doesn't have a permission for container-related directories and their owners"

    logger.trace('Step 5')
    dir="/mnt/common/container-overlays"
    list_check=["0755","containerd_u","containerd_g"]
    
    logger.trace('Step 6')
    assert stat_check(preinstalled_meter,dir,list_check),f"File {dir} doesn't have a permission for container-related directories and their owners"

    logger.trace('Step 7')
    dir="/usr/share/itron/container-overlays"
    list_check=["0755","root","root"]   

    logger.trace('Step 8')
    assert stat_check(preinstalled_meter,dir,list_check),f"File {dir} doesn't have a permission for container-related directories and their owners"

    logger.trace('Step 9')
    dir="/tmp/lxc_logs"
    list_check=["0777","containerd_u","containerd_g"]

    logger.trace('Step 10')
    assert stat_check(preinstalled_meter,dir,list_check),f"File {dir} doesn't have a permission for container-related directories and their owners"

    



    




